version: "3"

services:
  app:
    build: .
    volumes:
      - .:/go/src
    extra_hosts:
      - "host.docker.internal: 172.17.0.1" 

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
      - "9094:9094"
    environment:
      kafka_broker_id: 1
      kafka_offsets_topic_replication_factor: 1
      kafka_zookeeper_connect: zookeeper:2181
      kafka_inter_broker_listener_name: INTERNAL
      kafka_listeners: INTERNAL://:9092, OUTSIDE://:9094
      kafka_advertised_listeners: INTERNAL://kafka:9092, OUTSIDE:// host.docker.internal:9094
      kafka_listener_security_protocol_map: INTERNAL:PLAINTEXT, OUTSIDE:PLAINTEXT

    extra_hosts:
      - "host.docker.internal: 172.17.0.1"